# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432
    volumes:
      - ./database/create.sql:/docker-entrypoint-initdb.d/create.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080